[toolchain]
anchor_version = "0.32.0"

[features]
seeds = false
skip-lint = false

[workspace]
members = ["."]

# Program IDs - auto-updated by deploy script (npm run deploy)
[programs.localnet]
setto_payment = "5iZ49Z39KrQ8MLDq8gUWtAMmSJ5mTcUSvPvjau8NvNVB"

[programs.devnet]
setto_payment = "DXxCKeaee3YD1HeA1UcBxTiHGZYFDZQ34Q2bjY87Nyoc"

[programs.mainnet]
setto_payment = "DXxCKeaee3YD1HeA1UcBxTiHGZYFDZQ34Q2bjY87Nyoc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
